from langchain_groq import ChatGroq
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

load_dotenv()

model = ChatGroq(model="llama-3.3-70b-versatile", temperature=0.7)

prompt_1 = PromptTemplate.from_template("Generate detailed report on {topic}")
prompt_2 = PromptTemplate.from_template("Generate 3 point summary of the following  {text}")

parser = StrOutputParser()

chain_1 = prompt_1 | model | parser 

chain_2 = prompt_2 | model | parser

full_chain = chain_1 | chain_2

response_1 = chain_1.invoke({"topic":"Computers"})

full_response = full_chain.invoke({"topic":"Computers"})

print(response_1) # This will print the detailed report on Computers generated by the first chain.
print("\n===================================================\n")
print(full_response) # This will print the 3 point summary of the detailed report on Computers generated by the full chain. The output of the first chain is passed as input to the second chain to generate the summary.
